require: rubocop-rails
AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - config/**/*
    - lib/tasks/*
    - Gemfile
    - features/**/*
    - spec/**/*

# バージョン0.72以降は使えないので注意
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 40

FormatString:
  EnforcedStyle: percent

NumericLiterals:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing
